openapi: 3.0.0
info:
  title: Utopia Airline Ticketing System
  version: "1.0"
  contact:
    name: Utopia Support
    url: "https://support.utopia.local"
    email: support@utopia.local
  termsOfService: "https://utopia.local/tos"
  license:
    name: License
    url: "https://utopia.local/license"
  description: |-
    This API is designed to manage ticket reservations within Utopia Airlines. It can be used by:

    * Travellers
    * Travel agents
    * Airline counter agents.
servers:
  - url: "http://localhost:3000"
paths:
  /account/register:
    $ref: "components/paths/account-register.yaml"
  /accounts:
    $ref: "components/paths/accounts.yaml"
