openapi: 3.0.0
info:
  title: Utopia Airline Reservation System
  version: "1.0"
  contact:
    name: Utopia Support
    url: "https://support.utopia.local"
    email: support@utopia.local
  termsOfService: "https://utopia.local/tos"
  license:
    name: License
    url: "https://utopia.local/license"
  description: |-
    This API is designed to manage ticket reservations within Utopia Airlines. It can be used by:

    * Travellers
    * Travel agents
    * Airline counter agents.
servers:
  - url: "http://localhost:3000"
paths:

  /account:
    $ref: "components/paths/account.yaml"
  /account/register:
    $ref: "components/paths/account-register.yaml"

  /online/itineraries:
    $ref: "components/paths/online-itineraries.yaml"
  /online/itinerary/{itinerary_id}:
    $ref: "components/paths/online-itinerary_itineraryId.yaml"
  /online/itineraries/tickets/{ticket_id}:
    $ref: "components/paths/online-itineraries-tickets_ticketId.yaml"
  /online/flights?{params...}:
    $ref: "components/paths/online-flights.yaml"

  /agent/itineraries:
    $ref: "components/paths/agent-itineraries.yaml"
  /agent/itineraries/{itinerary_id}:
    $ref: "components/paths/agent-itineraries_itineraryId.yaml"
  /agent/itineraries/travelers/{traveler_id}:
    $ref: "components/paths/agent-itineraries-travelers_travelerId.yaml"
  /agent/itineraries/tickets/{ticket_id}:
    $ref: "components/paths/agent-itineraries-tickets_ticketId.yaml"
  /agent/itineraries/agency/{agency_id}:
    $ref: "components/paths/agent-itineraries-agency_agencyId.yaml"
  /agent/flights?{params...}:
    $ref: "components/paths/agent-flights.yaml"

  /counter/itineraries:
    $ref: "components/paths/counter-itineraries.yaml"
  /counter/itineraries/{itinerary_id}:
    $ref: "components/paths/counter-itineraries_itineraryId.yaml"
  /counter/itineraries/travelers/{traveler_id}:
    $ref: "components/paths/counter-itineraries-travelers_travelerId.yaml"
  /counter/itineraries/tickets/{ticket_id}:
    $ref: "components/paths/counter-itineraries-tickets_ticketId.yaml"
  /counter/travelers:
    $ref: "components/paths/counter-travelers.yaml"
  /counter/flights:
    $ref: "components/paths/counter-flights.yaml?{params...}"
